#!/bin/sh

# dumb zip wrapper, used in this project to make single-file python executables

bin_exists() { hash "$1" >/dev/null 1>&2; }

if bin_exists 7z; then
    7z a "$@"
elif bin_exists zip; then
    zip "$@"
else
    echo "please install 7z or zip"
fi
